dist: xenial
sudo: false

language: python
python:
  - "3.7"

env:
  - COLUMNS=80

# command to install dependencies
install:
  - "pip install -r requirements.txt"

# command to run tests
script: 
  - touch src/schema/ocl.yaml && make test

