name: Check Push and Pull Request

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  # repository_dispatch:
  #   types: trigger-check-pull-request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ ubuntu-latest, windows-latest ]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/checkout@v2
      with:
        submodules: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade tox
#        pip install mkdocs
#        pip install linkml
#        pip install Flask
#        pip install lark
#        pip install click  #used for CLI later on 
#        pip install pytest

    # - name: Check manifest
    #   run: tox -e manifest
    - name: Lint with flake8
      run: tox -e flake8
    # - name: Test with MyPy
    #   run: tox -e mypy
    - name: Test with pytest
      run: tox -e py


